AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sdk-apigw-lambda-ses

  Sample SAM Template for sdk-apigw-lambda-ses
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MainFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      Policies:
        Statement:
          Effect: "Allow"
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource: "*"
      Events:
        FunctionApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /contact
            Method: POST
